version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=sailfish #optional
      - PASS=sailfish #optional
    volumes:
      - /sharedfolders/AppData/transmission:/config
      - /sharedfolders/Downloads:/downloads
      - /sharedfolders/Media:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped