version: '3'

services:
  restart: always
  image: nginx:1.12
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./webapp/html:/webapp/html
  ports:
    - 80:80
#    - 443:443